PIofSF/force-app/main/default/objects/Module_Response__c/Module_Response__c.object-meta.xml
<CustomObject>
    <label>Module Response</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Module Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PIofSF/force-app/main/default/objects/Module_Response__c/fields/Status_Completed__c.field-meta.xml
<CustomField>
    <fullName>Status_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status Completed</label>
    <type>Checkbox</type>
</CustomField>

PIofSF/force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PIofSF/force-app/main/default/objects/Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>is the relationship MD with the question to which they belong</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PIofSF/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PIofSF/force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <label>Question Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PIofSF/force-app/main/default/objects/Question_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the records are going to be the answers</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

PIofSF/force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <label>Unit Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PIofSF/force-app/main/default/objects/Unit_Response__c/fields/Number_Tries__c.field-meta.xml
<CustomField>
    <fullName>Number_Tries__c</fullName>
    <label>Number Tries</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PIofSF/force-app/main/default/objects/Unit_Response__c/fields/StatusProgress__c.field-meta.xml
<CustomField>
    <fullName>StatusProgress__c</fullName>
    <label>StatusProgress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PIofSF/force-app/main/default/objects/Unit_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Responses</relationshipLabel>
    <relationshipName>Unit_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PIofSF/force-app/main/default/objects/Unit_Response__c/fields/Unit_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Unit_Lookup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit_Lookup</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Responses</relationshipLabel>
    <relationshipName>Unit_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PIofSF/force-app/main/default/classes/UnitService.cls
// the class almacena la logica para crear los records
public with sharing class UnitService {
    
    public static Boolean registerUnitResponse(Id unitId, String jsonAnswer) {
        
        //Database.SaveResult sp = Database.setSavePoint();
        
        Boolean booleanStatus = false;
        try {
            //fetch unit from database
            Unit__c unit = [SELECT Module__c, (SELECT Id, Number_Tries__c FROM Unit_Responses__r WHERE Module_Response__r.User__c =: UserInfo.getUserId() ORDER BY Number_Tries__c DESC LIMIT 1), (SELECT Id, Name FROM Questions__r) FROM Unit__c WHERE Id =: unitId];
            
            //verificar si ya existe un module response
            Module_Response__c moduleResp = [SELECT Id FROM Module_Response__c WHERE Module__c =: unit.Module__c AND User__c =: UserInfo.getUserId() AND Status_Completed__c = false];
            
            
            if (moduleResp == null){
                 //create and insert of module response
                moduleResp = new Module_Response__c (User__c = UserInfo.getUserId(), 
                    Module__c = unit.Module__c, Status_Completed__c = true);
                insert moduleResp;
            }
           
            //create and insert of unit response
            Unit_Response__c unitResp = new Unit_Response__c(Unit_Lookup__c = unitId, 
                Module_Response__c = moduleResp.Id, StatusProgress__c = 'Draft');
            //NTH ternario
            if(!unit.Unit_Responses__r.isEmpty()){
                unitResp.Number_Tries__c = unit.Unit_Responses__r[0].Number_Tries__c + 1;
            }else{
                unitResp.Number_Tries__c = 1;
            }
            insert unitResp;
            
            //create and upload question response
            Map<Id, Id> answerMap = (Map<Id, Id>)JSON.deserialize(jsonAnswer, Map<Id, Id>.class);
            List<Question_Response__c> questionRespList = new List<Question_Response__c>();
            
            //itero el Map con un set de key q me realiza el motodo keySet()
            //for (Id questionId : answerMap.keySet()) {
            for(Question__c question : unit.Questions__r){
            
                if (answerMap.containsKey(question.Id)){
                    Question_Response__c questionResp = new Question_Response__c(Question__c = question.Id, 
                    Unit_Response__c = unitResp.Id, Option__c = answerMap.get(question.Id));
                    questionRespList.add(questionResp);
                }else{
                    throw new CustomException('La pregunta ' + question.Name + ' no fue respondida y es requerida.');
                }
            } 
            insert questionRespList;
            
            //update the unit responses to answered to trigger the evaluation process
            unitResp.StatusProgress__c = 'Answered';
            update unitResp;
            
            booleanStatus = true;
            
        } catch (Exception e) {
            //Database.rollback(sp);
            throw e;
        }
        
        return booleanStatus;
    }
}